# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='last_posted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date posted'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='tweet_text',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
