# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_auto_20161213_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['last_posted_date', 'name']},
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
