# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_auto_20161214_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='newsletter_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date posted'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='newsletter_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
