# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_auto_20161215_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='newsletter_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date mailed'),
        ),
    ]
