# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0005_auto_20161215_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='newsletter_active',
            field=models.BooleanField(default=False),
        ),
    ]
