# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0006_recipient_newsletter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='can_donate_to',
            field=models.BooleanField(default=True),
        ),
    ]
