# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_recipient_can_donate_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
