# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0009_auto_20161230_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
