# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0010_recipient_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
