# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0011_auto_20170108_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='facebook_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
