# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0012_recipient_facebook_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='can_donate_to',
            field=models.BooleanField(default=True, verbose_name=b'Donate'),
        ),
    ]
