# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0013_auto_20170218_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'created on')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
