# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0014_suggestedrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='candidate_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'vote date'),
        ),
        migrations.AlterField(
            model_name='suggestedrecipient',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecipient',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecipient',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
