# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0009_auto_20161230_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.Recipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
